Repository Gomushim/frontend, pull requests merged in 2025-05, with the labels that each got.

#24 [api] 편지 api 추가
  package.json
  pnpm-lock.yaml
  src/app/App.tsx
  src/app/main.tsx
  src/app/router/routes.tsx
  src/assets/images/armybg.svg
  src/assets/images/character_default.svg
  src/assets/images/letter_green.svg
  src/assets/images/marinebg.svg
  src/assets/json/coupleconnect.json
  src/assets/json/pushalarm.json
  src/entities/check_status/queries.ts
  src/entities/check_status/service.ts
  src/entities/check_status/types.ts
  src/entities/coupleconnect/service.ts
  src/entities/coupleconnect/types.ts
  src/entities/emotion_status/mutation.ts
  src/entities/emotion_status/queries.ts
  src/entities/emotion_status/service.ts
  src/entities/emotion_status/types.ts
  src/entities/iscouple/queries.ts
  src/entities/maonboarding/mutation.ts
  src/entities/maonboarding/queries.ts
  src/entities/maonboarding/service.ts
  src/entities/maonboarding/types.ts
  src/entities/my_letter/queries.ts
  src/entities/my_letter/service.ts
  src/entities/my_letter/types.ts
  src/features/ma-section/DDaySection.tsx
  src/features/ma-section/LetterSection.tsx
  src/features/ma-section/MainHeader.tsx
  src/features/ma-section/ScheduleSection.tsx
  src/features/ma-section/SpecialDateSection.tsx
  src/features/ma-section/StatusSection.tsx
  src/features/ma-section/TopSection.tsx
  src/features/ma-section/index.ts
  src/features/ma-section/utils/EmotionSelector.tsx
  src/features/ma-section/utils/MainHeader.tsx
  src/pages/couplematch/CoupleContact.tsx
  src/pages/couplematch/index.ts
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/StatusPage.tsx
  src/pages/mainPage/index.ts
  src/pages/onboarding/Alarm.tsx
  src/pages/onboarding/Birthday.tsx
  src/pages/onboarding/FirstMeet.tsx
  src/pages/onboarding/MilitaryDay.tsx
  src/pages/onboarding/Nickname.tsx
  src/pages/onboarding/Onboarding.tsx
  src/pages/onboarding/Where.tsx
  src/pages/onboarding/index.ts
  src/shared/ui/datepicker.tsx
  src/shared/ui/drawer.tsx
  src/shared/ui/navbar.tsx
  src/stores/coupleStore.ts
  src/stores/maonboardingStore.ts
  src/stores/onboardingStore.ts
Labels: 🎨 Style, 📬 API, 🔨 Refactor

#26 Api/#20 calendar
  src/assets/images/noDday.svg
  src/entities/comment/index.ts
  src/entities/comment/model/index.ts
  src/entities/comment/model/request.type.ts
  src/entities/comment/model/response.type.ts
  src/entities/comment/mutaion.ts
  src/entities/comment/service.ts
  src/entities/comment/type.ts
  src/entities/d-day/index.ts
  src/entities/d-day/query.ts
  src/entities/d-day/queryKey.ts
  src/entities/d-day/service.ts
  src/entities/d-day/type.ts
  src/entities/letter/query.ts
  src/entities/letter/queryKey.ts
  src/entities/letter/service.ts
  src/entities/letter/type.ts
  src/entities/schedule/type.ts
  src/features/d-day/widgets/DdayList.tsx
  src/features/d-day/widgets/index.ts
  src/features/letter/utils/groupLettersByMonth.ts
  src/features/letter/widgets/DetailLetterBottomSheet.tsx
  src/features/letter/widgets/LetterCard.tsx
  src/features/letter/widgets/LetterList.tsx
  src/features/letter/widgets/MonthlyLettersView.tsx
  src/features/letter/widgets/index.ts
  src/pages/calendar/DdayListPage.tsx
  src/pages/calendar/LetterListPage.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useIntersect.ts
  src/shared/utils/date/formatdate.ts
Labels: 📬 API, 🍀병현

#28 Prototype
  package.json
  pnpm-lock.yaml
  src/assets/icons/kakao.svg
  src/assets/images/login.svg
  src/entities/d-day/mutation.ts
  src/entities/d-day/query.ts
  src/entities/d-day/queryKey.ts
  src/entities/d-day/service.ts
  src/entities/d-day/type.ts
  src/entities/letter/mutation.ts
  src/entities/schedule/mutation.ts
  src/entities/schedule/query.ts
  src/entities/schedule/queryKey.ts
  src/entities/schedule/service.ts
  src/features/letter/WriteLetterBottomSheet.tsx
  src/features/login/LoginButton.tsx
  src/features/mainpage/DDaySection.tsx
  src/features/mainpage/LetterSection.tsx
  src/features/mainpage/ScheduleSection.tsx
  src/features/mainpage/ui/MainHeader.tsx
  src/features/schedule/widgets/FatigueBottomSheet.tsx
  src/features/schedule/widgets/FatigueCard.tsx
  src/features/schedule/widgets/MainScheduleCardList.tsx
  src/features/schedule/widgets/MiniCalendar.tsx
  src/features/schedule/widgets/ScheduleCard.tsx
  src/features/schedule/widgets/index.ts
  src/pages/calendar/DdayListPage.tsx
  src/pages/calendar/NewSchedule.tsx
  src/pages/calendar/Root.tsx
  src/pages/calendar/ScheduleDetail.tsx
  src/pages/home/Home.tsx
  src/pages/home/index.ts
  src/pages/index.ts
  src/pages/login/Login.tsx
  src/shared/ui/button.tsx
Labels: ✨ Feature, 🍀병현

#37 Prototype
  package.json
  pnpm-lock.yaml
  src/app/router/routes.tsx
  src/entities/d-day/index.ts
  src/entities/d-day/model/index.ts
  src/entities/d-day/model/types.ts
  src/entities/d-day/mutation.ts
  src/entities/d-day/service.ts
  src/entities/d-day/store.ts
  src/entities/d-day/type.ts
  src/entities/letter/mutation.ts
  src/entities/letter/service.ts
  src/entities/letter/type.ts
  src/entities/schedule/mutation.ts
  src/entities/schedule/service.ts
  src/features/d-day/ui/EmojiSelector.tsx
  src/features/letter/WriteLetterBottomSheet.tsx
  src/features/letter/ui/LetterCard.tsx
  src/features/mypage/ui/MyPageHeader.tsx
  src/features/schedule/hooks/index.ts
  src/features/schedule/hooks/useInitializeScheduleFormFromCache.ts
  src/features/schedule/hooks/useScheduleForm.ts
  src/features/schedule/index.ts
  src/features/schedule/model/index.ts
  src/features/schedule/model/props.ts
  src/features/schedule/model/state.ts
  src/features/schedule/ui/AllDayToggleButton.tsx
  src/features/schedule/ui/ScheduleOverView.tsx
  src/pages/calendar/NewSchedule.tsx
  src/pages/calendar/ScheduleDetail.tsx
  src/pages/dday/NewDday.tsx
  src/pages/mypage/DisconnectPage.tsx
  src/shared/ui/alert-dialog.tsx
  src/shared/ui/button.tsx
  src/shared/ui/deleteAlert.tsx
  src/shared/ui/index.ts
  src/shared/ui/infoCard.tsx
Labels: ✨ Feature, 🔨 Refactor, 🍀병현

#45 [스플래쉬] 스플래쉬 추가
  public/splash/ios/10.2__iPad_landscape.png
  public/splash/ios/10.2__iPad_portrait.png
  public/splash/ios/10.5__iPad_Air_landscape.png
  public/splash/ios/10.5__iPad_Air_portrait.png
  public/splash/ios/10.9__iPad_Air_landscape.png
  public/splash/ios/10.9__iPad_Air_portrait.png
  public/splash/ios/11__iPad_Pro_M4_landscape.png
  public/splash/ios/11__iPad_Pro_M4_portrait.png
  public/splash/ios/11__iPad_Pro__10.5__iPad_Pro_landscape.png
  public/splash/ios/11__iPad_Pro__10.5__iPad_Pro_portrait.png
  public/splash/ios/12.9__iPad_Pro_landscape.png
  public/splash/ios/12.9__iPad_Pro_portrait.png
  public/splash/ios/13__iPad_Pro_M4_landscape.png
  public/splash/ios/13__iPad_Pro_M4_portrait.png
  public/splash/ios/4__iPhone_SE__iPod_touch_5th_generation_and_later_landscape.png
  public/splash/ios/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
  public/splash/ios/8.3__iPad_Mini_landscape.png
  public/splash/ios/8.3__iPad_Mini_portrait.png
  public/splash/ios/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_landscape.png
  public/splash/ios/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_portrait.png
  public/splash/ios/iPhone_11_Pro_Max__iPhone_XS_Max_landscape.png
  public/splash/ios/iPhone_11_Pro_Max__iPhone_XS_Max_portrait.png
  public/splash/ios/iPhone_11__iPhone_XR_landscape.png
  public/splash/ios/iPhone_11__iPhone_XR_portrait.png
  public/splash/ios/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_landscape.png
  public/splash/ios/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait.png
  public/splash/ios/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_landscape.png
  public/splash/ios/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait.png
  public/splash/ios/iPhone_16_Plus__iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_landscape.png
  public/splash/ios/iPhone_16_Plus__iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_portrait.png
  public/splash/ios/iPhone_16_Pro_Max_landscape.png
  public/splash/ios/iPhone_16_Pro_Max_portrait.png
  public/splash/ios/iPhone_16_Pro_landscape.png
  public/splash/ios/iPhone_16_Pro_portrait.png
  public/splash/ios/iPhone_16__iPhone_15_Pro__iPhone_15__iPhone_14_Pro_landscape.png
  public/splash/ios/iPhone_16__iPhone_15_Pro__iPhone_15__iPhone_14_Pro_portrait.png
  public/splash/ios/iPhone_16e__iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_landscape.png
  public/splash/ios/iPhone_16e__iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait.png
  public/splash/ios/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_landscape.png
  public/splash/ios/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait.png
  public/splash/ios/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_landscape.png
  public/splash/ios/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait.png
  public/splash/ios/icon.png
  vite.config.ts
Labels: ✨ Feature, 🍀병현

#43 [디데이] 디데이 관련 기능 구현 및 수정
  src/app/App.tsx
  src/app/router/routes.tsx
  src/entities/d-day/model/types.ts
  src/entities/d-day/mutation.ts
  src/entities/d-day/query.ts
  src/entities/d-day/service.ts
  src/features/d-day/hooks/index.ts
  src/features/d-day/hooks/useInitializeDdayFormFromCache.ts
  src/features/d-day/hooks/useNewDdayForm.ts
  src/features/d-day/index.ts
  src/features/d-day/model/index.ts
  src/features/d-day/model/state.ts
  src/features/d-day/ui/DdayCard.tsx
  src/pages/calendar/Root.tsx
  src/pages/dday/DdayListPage.tsx
  src/pages/dday/NewDday.tsx
  src/pages/mainPage/MainPage.tsx
Labels: 📬 API, 🔨 Refactor, 🍀병현

#46 [수정사항] 디자인 및 오류 수정
  src/assets/images/character/default_common.svg
  src/assets/images/character/focus_angry.svg
  src/assets/images/character/focus_common.svg
  src/assets/images/character/focus_happy.svg
  src/assets/images/character/focus_miss.svg
  src/assets/images/character/focus_sad.svg
  src/assets/images/character/focus_tired.svg
  src/assets/images/character/focus_worry.svg
  src/assets/images/character/inactive_angry.svg
  src/assets/images/character/inactive_common.svg
  src/assets/images/character/inactive_miss.svg
  src/assets/images/character/inactive_tired.svg
  src/assets/images/character/inactive_worry.svg
  src/features/login/LoginButton.tsx
  src/features/mainpage/LetterSection.tsx
  src/features/mainpage/ui/EmotionSelector.tsx
  src/pages/mainPage/CoupleContactPage.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/StatusPage.tsx
  src/pages/mainPage/initpage/FirstMeet.tsx
  src/pages/mainPage/initpage/MilitaryDay.tsx
  src/pages/mainPage/initpage/Where.tsx
  src/pages/mypage/editpage/BirthdayEditPage.tsx
  src/pages/mypage/editpage/FirstMeetEditPage.tsx
  src/pages/mypage/editpage/MilitaryEditPage.tsx
  src/pages/mypage/editpage/NicknameEditPage.tsx
  src/pages/onboarding/Alarm.tsx
  src/pages/onboarding/Birthday.tsx
  src/pages/onboarding/Nickname.tsx
  src/shared/ui/input.tsx
Labels: 🎨 Style, 🐞 BugFix

#48 QA에서 발생한 오류 수정
  src/entities/d-day/model/types.ts
  src/entities/d-day/mutation.ts
  src/entities/schedule/type.ts
  src/features/d-day/hooks/useInitializeDdayFormFromCache.ts
  src/features/d-day/ui/DdayCard.tsx
  src/features/mainpage/DDaySection.tsx
  src/features/schedule/ui/Calendar.tsx
  src/features/schedule/ui/CalendarBottomSheet.tsx
  src/features/schedule/ui/CalendrDdayCard.tsx
  src/features/schedule/ui/ScheduleCard.tsx
  src/features/schedule/ui/ScheduleCardList.tsx
  src/features/schedule/ui/TitleInput.tsx
  src/features/schedule/ui/index.ts
  src/pages/calendar/NewSchedule.tsx
  src/pages/dday/DdayListPage.tsx
  src/pages/dday/NewDday.tsx
  src/pages/letter/LetterListPage.tsx
  src/shared/hooks/useIntersect.ts
  src/shared/ui/countInput.tsx
  src/shared/ui/index.ts
  src/shared/ui/infoCard.tsx
  src/shared/ui/shadcnInput.tsx
  src/shared/ui/topbar.tsx
Labels: 🐞 BugFix, 🍀병현

#49 [수정사항] QA 반영 수정
  src/entities/couple_birthday/queries.ts
  src/entities/couple_nickname/queries.ts
  src/entities/init_setting/queries.ts
  src/entities/iscouple/queries.ts
  src/entities/main_anniversary/queries.ts
  src/entities/main_letter/queries.ts
  src/entities/main_status/queries.ts
  src/entities/mypage_info/queries.ts
  src/entities/push_alarm/queries.ts
  src/features/d-day/ui/DdayDateBottomSheet.tsx
  src/features/letter/ui/LetterCard.tsx
  src/features/mainpage/DDaySection.tsx
  src/features/mainpage/LetterSection.tsx
  src/features/mainpage/SpecialDateSection.tsx
  src/features/mainpage/StatusSection.tsx
  src/features/mypage/AlarmSettingSection.tsx
  src/features/mypage/ProfileCardSection.tsx
  src/features/mypage/StatusSection.tsx
  src/features/schedule/ui/CalendarBottomSheet.tsx
  src/features/schedule/ui/DateBottomSheet.tsx
  src/pages/mainPage/StatusPage.tsx
  src/pages/mainPage/initpage/FirstMeet.tsx
  src/pages/mainPage/initpage/MilitaryDay.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/ProfileInfoPage.tsx
  src/pages/mypage/editpage/BirthdayEditPage.tsx
  src/pages/mypage/editpage/FirstMeetEditPage.tsx
  src/pages/mypage/editpage/MilitaryEditPage.tsx
  src/pages/onboarding/Birthday.tsx
  src/shared/ui/sheet.tsx
  src/widgets/datepicker/ui/datepicker.tsx
  src/widgets/datepicker/ui/index.ts
Labels: 🎨 Style, 🐞 BugFix

#50 [ 스타일 수정 ] 자잘한 오류 및 디자인 수정
  index.html
  src/entities/mypage_info/queries.ts
  src/features/mainpage/DDaySection.tsx
  src/features/mainpage/LetterSection.tsx
  src/features/mypage/AlarmToggleList.tsx
  src/features/mypage/StatusSection.tsx
  src/pages/mainPage/CoupleContactPage.tsx
  src/pages/onboarding/Alarm.tsx
Labels: 🎨 Style, 🐞 BugFix, 🍀유민

#55 [수정사항] QA 1차 수정
  src/assets/images/navybg.svg
  src/entities/couple_nickname/queries.ts
  src/entities/init_setting/queries.ts
  src/entities/iscouple/queries.ts
  src/entities/main_anniversary/queries.ts
  src/entities/main_letter/queries.ts
  src/entities/main_status/queries.ts
  src/features/mainpage/LetterSection.tsx
  src/features/mainpage/SpecialDateSection.tsx
  src/features/mainpage/TopSection.tsx
  src/pages/mainPage/CoupleContactPage.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/onboarding/Alarm.tsx
  src/pages/onboarding/Nickname.tsx
  src/shared/styles/tailwind.config.js
  src/shared/ui/loading.tsx
Labels: 🐞 BugFix, 🍀유민

#57 [수정사항] QA 2차 수정
  src/assets/json/pushalarm.json
  src/entities/edit_info/mutation.ts
  src/features/mainpage/LetterSection.tsx
  src/pages/mainPage/CoupleContactPage.tsx
Labels: 🎨 Style, 🐞 BugFix, 🍀유민
