Repository Gomushim/frontend, pull requests merged in 2025-04, with the labels that each got.

#2 [Setting] 디자인시스템 적용
  public/fonts/Pretendard.woff2
  src/index.css
  tailwind.config.js
Labels: 🍀유민, 🔧Setting

#6 🔧setting: 디자인시스템 색상변경
  tailwind.config.js
Labels: 🔧Setting

#7 [컴포넌트] 공통 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/assets/images/calendar_black.svg
  src/assets/images/calendar_gray.svg
  src/assets/images/checked.svg
  src/assets/images/delete.svg
  src/assets/images/home_black.svg
  src/assets/images/home_gray.svg
  src/assets/images/mypage_black.svg
  src/assets/images/mypage_gray.svg
  src/assets/images/react.svg
  src/assets/images/unchecked.svg
  src/componenets/Button/Button.tsx
  src/componenets/CheckBox/CheckBox.tsx
  src/componenets/Input/Input.tsx
  src/componenets/NavBar/NavBar.tsx
  src/componenets/Text/Text.tsx
  src/components/ui/button.tsx
  src/components/ui/checkbox.tsx
  src/vite-env.d.ts
  tailwind.config.js
  vite.config.ts
Labels: ✨ Feature, 🍀유민

#11 [온보딩] 온보딩 페이지 구현
  package.json
  pnpm-lock.yaml
  src/assets/images/back.svg
  src/assets/images/close.svg
  src/assets/images/react.svg
  src/componenets/Button/Button.tsx
  src/componenets/CheckBox/CheckBox.tsx
  src/componenets/Input/Input.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/datepicker.tsx
  src/components/ui/drawer.tsx
  src/components/ui/input.tsx
  src/components/ui/navbar.tsx
  src/components/ui/textinput.tsx
  src/pages/index.ts
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/index.ts
  src/pages/onboading/index.ts
  src/pages/onboarding/Alarm.tsx
  src/pages/onboarding/Birthday.tsx
  src/pages/onboarding/CoupleContact.tsx
  src/pages/onboarding/FirstMeet.tsx
  src/pages/onboarding/MilitaryDay.tsx
  src/pages/onboarding/Nickname.tsx
  src/pages/onboarding/Onboarding.tsx
  src/pages/onboarding/Where.tsx
  src/pages/onboarding/components/progressheader.tsx
  src/pages/onboarding/index.ts
  src/utils/formatdate.ts
  src/utils/router/routes.tsx
  vite.config.ts
Labels: ✨ Feature, 🎨 Style, 🍀유민

#13 [캘린더] 캘린더 페이지 UI 및 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/assets/icons/bottomArrow.svg
  src/assets/icons/cake.svg
  src/assets/icons/calendar.svg
  src/assets/icons/grayCalendar.svg
  src/assets/icons/grayClock.svg
  src/assets/icons/hambuk.svg
  src/assets/icons/heart.svg
  src/assets/icons/infoCardArrow.svg
  src/assets/icons/leftArrow.svg
  src/assets/icons/plus.svg
  src/assets/icons/rightArrow.svg
  src/assets/icons/taravel.svg
  src/components/calendar/Calendar.tsx
  src/components/calendar/DateSelector.tsx
  src/components/calendar/DdayCard.tsx
  src/components/calendar/EmojiSelector.tsx
  src/components/calendar/FatigueBottomSheet.tsx
  src/components/calendar/FatigueCard.tsx
  src/components/calendar/LetterCard.tsx
  src/components/calendar/ScheduleCard.tsx
  src/components/calendar/TimeSelector.tsx
  src/components/calendar/Topbar.tsx
  src/components/calendar/index.ts
  src/components/ui/DateText.tsx
  src/components/ui/Divider.tsx
  src/components/ui/InCard.tsx
  src/components/ui/button.tsx
  src/components/ui/drawer.tsx
  src/components/ui/switch.tsx
  src/hooks/useToggle.ts
  src/pages/Layout/ProtectedLayout.tsx
  src/pages/Layout/index.ts
  src/pages/calendar/NewSchedule.tsx
  src/pages/calendar/Root.tsx
  src/utils/date/FomatDateToKr.ts
  src/utils/router/routes.tsx
  tailwind.config.js
Labels: ✨ Feature, 🍀병현

#21 ♻️ Refactor: 컴포넌트에서 유틸 함수 분리 후 타입 정리
  src/features/letter/utils/groupLettersByMonth.ts
  src/features/letter/utils/index.ts
  src/features/letter/widgets/MonthlyLettersView.tsx
  src/shared/utils/date/formatdate.ts
Labels: 🔨 Refactor, 🍀병현
